apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: 123384174556.dkr.ecr.us-east-1.amazonaws.com/notifications:latest
        name: notifications
        env:
        - name: PORT
          value: '3000'
        - name: GOOGLE_OAUTH_CLIENT_ID
          value: 498713664366-37n9ee0fdj8bkthvafegpofs0liorcni.apps.googleusercontent.com
        - name: SMTP_USER
          value: imuchene@gmail.com
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google
              key: clientSecret
        - name: GOOGLE_OAUTH_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: google
              key: refreshToken
        ports:
          - containerPort: 3000